"""
LLM visualization module.

This module provides visualization functionality for LLM-based forecasting results,
migrated from visualize_llm.py.
"""

import pandas as pd
import numpy as np
import os
import json
import matplotlib.pyplot as plt


def plot_prediction(indate, input_data, outdate, output_data, prediction_data,
                   dataset_name, model_name, data_id, date_start, img_path,
                   figsize=(15, 7), dpi=300):
    """
    Create prediction visualization plot for LLM results.
    
    Args:
        indate: Input timestamps
        input_data: Input time series data
        outdate: Output timestamps
        output_data: Ground truth values
        prediction_data: Model predictions
        dataset_name: Name of the dataset
        model_name: Name of the model
        data_id: Data subset ID
        date_start: Sample date identifier
        img_path: Path to save the image
        figsize: Figure size tuple (width, height)
        dpi: Resolution in dots per inch
    """
    plt.figure(figsize=figsize, dpi=dpi)
    plt.plot(indate, input_data, label='Input History')
    plt.plot(outdate, output_data, label='Ground Truth')
    plt.plot(outdate, prediction_data, label='Prediction', linestyle='--')
    plt.title(f'Prediction Visualization for {dataset_name}: {data_id}, Model: {model_name}, Sample: {date_start}')
    plt.xlabel('Timestamp')
    plt.ylabel('Value')
    plt.legend()
    plt.grid(True)
    plt.gcf().autofmt_xdate()
    
    img_dir = os.path.dirname(img_path)
    if img_dir and not os.path.exists(img_dir):
        os.makedirs(img_dir)
        print(f"Created directory: {img_dir}")

    plt.savefig(img_path)
    plt.close()
    print(f"Prediction plot saved to {img_path}")


def visualize(config, plotting_config=None):
    """
    Visualize LLM-based forecasting results from JSON files.
    
    This function reads prediction results from JSON files generated by LLM experiments
    and creates visualizations comparing input history, ground truth, and predictions.
    
    Args:
        config: dotdict containing visualization configuration with structure:
            - visualization: {ckpt_base, ckpt_id, data_id, date_start, img_path, task}
            - model: {name} (for display)
            - data: {name} (for display)
        plotting_config: Optional dotdict with plotting parameters:
            - figure: {figsize, dpi}
    
    Example:
        >>> from cli.config.loader import load_config_with_nested
        >>> config_hierarchy = load_config_with_nested("configs/experiments/llm_solar.yaml")
        >>> visualize(config_hierarchy['primary'], config_hierarchy['nested'].get('plotting'))
    """
    vis_config = config.visualization
    
    # Extract plotting parameters from subconfig if available
    if plotting_config:
        figsize = tuple(plotting_config.figure.get('figsize', [15, 7]))
        dpi = plotting_config.figure.get('dpi', 300)
    else:
        figsize = (15, 7)
        dpi = 300
    
    # Load from JSON
    json_path = os.path.join(vis_config.ckpt_base, vis_config.ckpt_id, vis_config.data_id, f"{str(vis_config.date_start)}_result.json")
    
    if not os.path.exists(json_path):
        print(f"Error: JSON file not found at {json_path}")
        return
    
    print(f"Loading data from: {json_path}")
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Extract data from JSON
    x_table = data.get('x_table', [])
    y_table = data.get('y_table', [])
    pred_table = data.get('pred', [])

    if not x_table or not y_table or not pred_table:
        raise ValueError("JSON file must contain 'x_table', 'y_table', and 'pred' keys with non-empty data.")

    x_time = [np.int64(item[0]) for item in x_table]
    input_np = np.array([float(item[1]) for item in x_table])

    y_time = [np.int64(item[0]) for item in y_table]
    output_np = np.array([float(item[1]) for item in y_table])

    prediction_np = np.array([float(item[1]) for item in pred_table])

    # Visualization
    print(f"--- Visualizing data for ID: {vis_config.data_id}, Sample: {vis_config.date_start} ---")

    indate_dt = pd.to_datetime([str(i) for i in x_time], format='%Y%m%d%H%M%S')
    outdate_dt = pd.to_datetime([str(i) for i in y_time], format='%Y%m%d%H%M%S')

    img_path = os.path.join(vis_config.img_path, vis_config.task, f"{vis_config.ckpt_id}_subset-{vis_config.data_id}_date-{vis_config.date_start}.png")

    plot_prediction(indate=indate_dt,
                    input_data=input_np,
                    outdate=outdate_dt,
                    output_data=output_np,
                    prediction_data=prediction_np,
                    dataset_name=config.data.name,
                    model_name=config.model.name,
                    data_id=vis_config.data_id,
                    date_start=vis_config.date_start,
                    img_path=img_path,
                    figsize=figsize,
                    dpi=dpi)

